team_discussion: False
summarize: True
thought: False
test_role: "Servant"
naive_summary: "10-last"
agent_summary: "full-history" # either `10-last` or `full-history`
logging: "DEBUG"

prompts:
  INTRODUCTION: >
    You're playing a game called The Resistance: Avalon.


    The Resistance: Avalon is the game of hidden loyalty. Players come from two sdies, Good and Evil.


    Good wins the game by successfully completing three Quests. Evil wins if three Quests end in failure. Evil can also win by assassinating Merlin at game's end or if a Quest cannot be undertaken.


    Players may make any claims during the game, at any point in the game. Discussion, deception, accusation, and logical deduction are all equally important in order for Good to prevail or Evil to rule the day.


    A team will be accepted if over half of the players vote to support it. A quest will succeed only if all the players on the quest vote to support the quest.
  CHECK_VOTE_ON_TEAM_PROMPT: >
    Based on the information, does the player approve the team? Please answer with the following template:

    Answer: {Yes|No}

  CHECK_VOTE_ON_QUEST_PROMPT: >
    Based on the information, does the player support the quest? Please answer with the following template:

    Answer: {Yes|No}

  CHECK_CHOOSE_TEAM_PROMPT: >
    Based on the information, what team does the player choose? Please answer with the following template:

    Answer: [player_ids]

  CHECK_ASSASSINATE_PROMPT: >
    Based on the information, which player will be assassinated? Please answer with the following template:

    Answer: [player_id_num]
  
  DISCUSSION_PROMPT: "Statement from Leader {player_list[leader]}: \n\"{statement}\"\nAnd words from other players:\n{' '.join(discussion_history)}\n This is discussion phase, and you don't need to take an action. Please discuss about words from the leader and other players with just one sentence."

# To test the with all naive agents, set team_discussion to False

####### Passed Tests #######
# team_discussion: False 
# naive_summary: "10-last"
# agent_summary: "10-last"
############################
# team_discussion: True 
# naive_summary: "10-last"
# agent_summary: "10-last"
############################