module: "Multiagent"
parameters:
- module: "src.agents.RandomAgent"
  parameters:
      name: "Random-Agent"
      num_players: 5
      id: 0
      seed: 42
      api_args:
          model: "gpt-3.5-turbo"
          base: "None"
          timeout: 120
- module: "src.agents.RandomAgent"
  parameters:
      name: "Random-Agent"
      num_players: 5
      id: 1
      seed: 42
      api_args:
          model: "gpt-3.5-turbo"
          base: "None"
          timeout: 120
- module: "src.agents.RandomAgent"
  parameters:
      name: "Random-Agent"
      num_players: 5
      id: 2
      seed: 42
      api_args:
          model: "gpt-3.5-turbo"
          base: "None"
          timeout: 120
- module: "src.agents.RandomAgent"
  parameters:
      name: "Random-Agent"
      num_players: 5
      id: 3
      seed: 42
      api_args:
          model: "gpt-3.5-turbo"
          base: "None"
          timeout: 120
- module: "src.agents.RandomAgent"
  parameters:
      name: "Random-Agent"
      num_players: 5
      id: 4
      seed: 42
      api_args:
          model: "gpt-3.5-turbo"
          base: "None"
          timeout: 120