module: "Multiagent"
parameters:
- module: "src.agents.RandomAgent"
  parameters:
      name: "Random-Agent"
      num_players: 5
      seed: 42
- module: "src.agents.RandomAgent"
  parameters:
      name: "Random-Agent"
      num_players: 5
      seed: 42
- module: "src.agents.RandomAgent"
  parameters:
      name: "Random-Agent"
      num_players: 5
      seed: 42
- module: "src.agents.api_agents.OpenAIChatCompletion"
  parameters:
      name: "gpt-3.5"
      api_args:
          model: "gpt-3.5-turbo"
          key: ""
          base: "None"
          timeout: 120
- module: "src.agents.RandomAgent"
  parameters:
      name: "Random-Agent"
      num_players: 5
      seed: 42
    