module: "Multiagent"
parameters:
- module: "src.agents.Claude"
  parameters:
      id: 0
      name: "claude-v2"
      api_args:
          model: "claude-v1.3"
          # key: <assign your key here>
          max_tokens_to_sample: 256
- module: "src.agents.RandomAgent"
  parameters:
      id: 1
      name: "Random-Agent"
      num_players: 5
      seed: 42
      api_args:
          model: "gpt-3.5-turbo"
          base: "None"
          timeout: 120
- module: "src.agents.RandomAgent"
  parameters:
      id: 2
      name: "Random-Agent"
      num_players: 5
      seed: 42
      api_args:
          model: "gpt-3.5-turbo"
          base: "None"
          timeout: 120
- module: "src.agents.RandomAgent"
  parameters:
      id: 3
      name: "Random-Agent"
      num_players: 5
      seed: 42
      api_args:
          model: "gpt-3.5-turbo"
          base: "None"
          timeout: 120
- module: "src.agents.RandomAgent"
  parameters:
      id: 4
      name: "Random-Agent"
      num_players: 5
      seed: 42
      api_args:
          model: "gpt-3.5-turbo"
          base: "None"
          timeout: 120