import: definition.yaml

concurrency:
  task:
    avalon-dev-naive: 1
  agent:
    mixtral: 1

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - mixtral 
    task:
      # - avalon-dev-multi
      # - avalon-dev-single
      - avalon-dev-naive

output: "outputs/{TIMESTAMP}"
