import: definition.yaml

concurrency:
  task:
    avalon-dev-multi: 3
  agent:
    gpt-3.5-turbo-0613: 3

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-3.5-turbo-0613
    task:
      - avalon-dev-multi

output: "outputs/{TIMESTAMP}"
