module: "src.agents.OpenAIChatCompletion"
parameters:
    name: "gpt-4"
    api_args:
        model: "gpt-4"
        key: "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"
        base: "None"
        timeout: 120
