default:
  module: "src.server.tasks.GOPS.GOPSBench"
  parameters:
    concurrency: 5
    num_games: 20
    num_turns: 7

gops-dev-naive:
  parameters:
    name: "gops-dev-naive"
    agent_list: ["mcts", "alphabeta"]

gops-dev-single:
  parameters:
    name: "gops-dev-single"
    agent_list: ["naive", "llm"]

gops-dev-multi:
  parameters:
    name: "gops-dev-multi"
    agent_list: ["llm", "llm"]